package com.anaamalais.salescrm.Utils;

public class Constants {

    public static String IS_LOGIN="is_login";
    public static String BASE_URL ="http://atcrm.cloudnowtech.com/web/";
    public static String TOKEN = "token";
    public static String USER_ID ="UserID";
    public static String USER_TYPE="UserTupe";
    public static String EMP_NAME = "Emp_Name";
    public static String EMP_ID = "Emp_Id";
    public static String DEVICE_ID = "deviceid";
    public static String CUSTOMER_NAME = "Customer_name";
    public static String CUSTOMER_PHONE = "Customer_phone";
    public static String CUSTOMER_ADDRESS= "Customer_Address";
    public static String FOLLOWUPDATE= "followupdate";
    public static String FOLLOWUPTIME = "followuptime";
    public static String FOLLOWUPTYPE  = "followuptype";
    public static String DEVICEID = "deviceid";
    public static String CONTACT_ID = "contact_id";
    public static String TITLEID = "titleid";
    public static String PROSPECTCATEGORY = "PROSPECTCATEGORY";
    public static String FOLLOWUPID = "followupid";
    public static String DLNUMBER = "dlnumber";
    public static String DLPHOTO = "dlphoto";
    public static String TDSCHEDULEDON = "tdscheduledon";
    public static String DROP_REASON_ID = "dropreasonid";
    public static String TESTDRIVEID = "testdriveid";
    public static String OVERALLTDEXPERIANCE = "eexp";
    public static String OVERALLCONDITIONOFVEHICLE = "OVERALLCONDITIONOFVEHICLE";
    public static String SALES_CONSULTANTKNOWLEDGEOFTHEPRODUCT = "SALES_CONSULTANTKNOWLEDGEOFTHEPRODUCT";
    public static String OVERALLSALESCONSULTANTKNOWLEDGE_EXPERIENCE = "OVERALLSALESCONSULTANTKNOWLEDGE_EXPERIENCE";
    public static String STATUS_ID= "STATUS_ID";
    public static String BOOKINGCOMPLETEDID = "BOOKINGCOMPLETEDID";
    public static String BOOKINGMODEANDSUFFIX  = "BOOKINGMODEANDSUFFIX";
    public static String INTERIORCOLOR = "INTERIORCOLOR";
    public static String EXTERIORCOLOR = "EXTERIORCOLOR";
    public static String PAYMENTMODE = "PAYMENTMODE";
    public static String BOOKINGTIME = "BOOKINGTIME";
    public static String BOOKINGDATE = "BOOKINGDATE";
    public static String BOOKINGAMOUNT = "BOOKINGAMOUNT";
    public static String FIFTEEN_dAY_FOLLOWUP_ID = "FIFTEEN_dAY_FOLLOWUP_ID";
    public static String STATUSID = "STATUSID";
    public static String COMMENT = "COMMENT";
    public static String FOLLOWUP_REMARK = "FOLLOWUP_REMARK";
    public static String DELIVERY_COMPLETED_ID = "DELIVERY_COMPLETED_ID";
    public static String TIME = "TIME";
    public static String DATE = "DATE";
    public static String REFNAME = "REFNAME";
    public static String REFPHONE = "REFPHONE";
    public static String ACCESSORIES_FITMENT_STATUS = "ACCESSORIES_FITMENT_STATUS";
    public static String AF_WAITING_REASON = "AF_WAITING_REASON";
    public static String EXTENDED_WARRANTY = "EXTENDED_WARRANTY";
    public static String FASTAG = "FASTAG";
    public static String RTO_PROCESS = "RTO_PROCESS";
    public static String RTO_WAITING_REASON = "RTO_WAITING_REASON";
    public static String ALLOCATION_PDI = "ALLOCATION_PDI";
    public static String PREFERRED_RTO_DATE = "PREFERRED_RTO_DATE";
    public static String INVOICE_COMPLETED_COMMENTS = "INVOICE_COMPLETED_COMMENTS";
    public static String INVOICE_COMPLETED_ID = "INVOICE_COMPLETED_ID";

    public static String BOOKING_FOLLOWUP_DETAILS_ID = "BOOKING_FOLLOWUP_DETAILS_ID";
    public static String VEHICLE_ALLOTTED = "VEHICLE_ALLOTTED";
    public static String VEHICLE_NOT_ALLOTTED_REASON = "VEHICLE_NOT_ALLOTTED_REASON";
    public static String EX_SHOWROOM_PRICE = "EX_SHOWROOM_PRICE";
    public static String  TCS =  "TCS";
    public static String TCS_AMOUNT =  "TCS_AMOUNT";
    public static String ROAD_TAX =  "ROAD_TAX";
    public static String INSURANCE =  "INSURANCE";
    public static String REGISTRATION =  "REGISTRATION";
    public static String ACCESSORIES =  "ACCESSORIES";
    public static String WARRANTY =  "WARRANTY";
    public static String FASTAGG =  "FASTAGG";
    public static String OFFERS  =  "OFFERS";
    public static String NET_AMOUNT =  "NET_AMOUNT";
    public static String EXPECTED_DOWNPAYMENT_AMOUNT =  "EXPECTED_DOWNPAYMENT_AMOUNT";
    public static String EXPECTED_DOWNPAYMENT_DATE =  "EXPECTED_DOWNPAYMENT_DATE";
    public static String EXPECTED_INVOICE_DATE =  "EXPECTED_INVOICE_DATE";
    public static String PAPER_DOCUMENTS_COLLECTED =  "PAPER_DOCUMENTS_COLLECTED";
    public static String LOGIN_COMPLETED_DATE =  "LOGIN_COMPLETED_DATE";
    public static String LOGIN_COMPLETED  =  "LOGIN_COMPLETED";
    public static String QUERY_CLEARANCE =  "QUERY_CLEARANCE";
    public static String LOAN_AMOUNT  =  "LOAN_AMOUNT";
    public static String FOLLOW_UP_DATE =  "FOLLOW_UP_DATE";
    public static String  FOLLOW_UP_TIME =  "FOLLOW_UP_TIME";
    public static String FOLLOW_UP_TYPE =  "FOLLOW_UP_TYPE";
    public static String FOLLOW_UP_REMARK =  "FOLLOW_UP_REMARK";
    public static String PRE_DELIVERY_ID =  "PRE_DELIVERY_ID";
    public static String MODE =  "mode";
    public static String VEHICLEID = "vehicleid";
    public static String MODEL_VARIANT = "modelvariant";
    public static String FINANCEPITCHID = "financepitchid";
    public static String INSURANCEPITCHID = "insurancepitchid";
    public static String SPINNERTITLEID = "spinnertitleid";
    public static String SPINNERENQUIRYID = "spinnerenquiryid";
    public static String SPINNERSOURCEID = "spinnersourceid";
    public static String INTERIOR = "interior";
    public static String EXTEREIOR = "extereior";
    public static String PAYMENTSMODE = "paymentsmode";
    public static String MODEL_ID = "modelid";
    public static String PRICEINT = "priceint";
    public static String PRICEEXT = "priceext";
    public static String PRICEUTL = "priceutl";
    public static String MODELIMAGE = "modelimage";
    public static String COLORID = "colorid";
    public static String VARIANTID = "variantid";
    public static String ACCESSORIESLIST = "accessorieslist";




    public static class ErrorCodes {
        public static final int NOT_CONNECTED_TO_INTERNET = 503;
        public static final int BAD_REQUEST = 500;
        public static final int CART_EMPTY = 204;
        public static final int UNDEFINED = -1;
        public static final int ERROR_PLACING_ORDER = -2;
    }
    public static final String BannerIndividualFragment_Data_Extra = "BannerIndi";
}
